数字

In [2]:
int_num=10
float_num=10.00
print(int_num)
print(float_num)

10
10.0


In [4]:
float_num=10.000
print(float_num)
print("%f"%float_num)
print("%.2f"%float_num)
print("%.4f"%float_num)

10.0
10.000000
10.00
10.0000


字符串

In [5]:
string1="hello_world"
string2="hello__world2"
print(string1)
print(string2)

hello_world
hello__world2


In [7]:
string ="myhelloworld"
string0=string[0]
string1=string[0:12]
s3=string[0:5]
s4=string[-1]
s5=string[-5:]
s6=string[6:]
s7=string[:5]
print(string,string1,s3,s4,s5,s6,s7)

myhelloworld myhelloworld myhel d world oworld myhel


列表

In [9]:
list1=["hello_world",100,10.2]
list2=[12,3,'HI']
print(list1)
print(list1[0])
print(list1[1:])
print(list1[-1])
print(list1+list2)

['hello_world', 100, 10.2]
hello_world
[100, 10.2]
10.2
['hello_world', 100, 10.2, 12, 3, 'HI']


元组

In [15]:
tuple1=("hello",12,10.9)
tuple2=(2,-1,321)
print(tuple1)
print(tuple1[0])
print(tuple1[1:])
print(tuple1[-1])
print(tuple1+tuple2)

('hello', 12, 10.9)
hello
(12, 10.9)
10.9
('hello', 12, 10.9, 2, -1, 321)


字典

In [16]:
dict_1={}
dict_1["one"]="This is one"
dict_1[2]="TWO"
dict_info={"name":"tang","num":"7272","city":"GL"}
print(dict_1["one"])
print(dict_1[2])
print(dict_info)
print(dict_info.keys())
print(dict_info.values())

This is one
TWO
{'name': 'tang', 'num': '7272', 'city': 'GL'}
dict_keys(['name', 'num', 'city'])
dict_values(['tang', '7272', 'GL'])


运算

In [19]:
a=5
b=2
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a//b)#取整运算
print(a%b)
print(a**b)

7
3
2.5
10
2
1
25


比较运算符

In [20]:
a=5
b=2
print(a==b)
print(a!=b)
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)

False
True
True
True
False
False


布尔运算符


In [21]:
a=True
b=False
print(a and b)
print(a or b)
print(not a)

False
True
False


In [23]:
a=3
b=1
c=3
print(a>b and b<c)
print(not a>b)

True
False


成员运算符

In [24]:
list1=["I","am","smart"]
a="I"
print(a in list1)
b="YOU"
print(b in list1)



True
False


身份运算符

In [25]:
a=100
b=100
print(id(a)) #a内存地址
print(id(b))
print("a is b",a is b)
print("a is not b",a is not b)
print("a==b",a==b)
#is 比较变量是否 属于同一对象 == 比较大小
#结果不一定和py解释器有关

140715352894960
140715352894960
a is b True
a is not b False
a==b True


条件判断语句

In [27]:
num=10
if num==10:
    print("NUM==10")
elif num>10:
    print("NUM>10")
else :
    print("hh")

NUM==10


In [28]:
num=8
if num==10:
    print("NUM==10")
elif num>10:
    print("NUM>10")
else :
    print("hh")


hh


循环语句

In [29]:
num=0
while(num<10):
    print(num)
    num+=1

0
1
2
3
4
5
6
7
8
9


In [30]:
num=10
for i in range(10):
    if i<num:
        print(i)



0
1
2
3
4
5
6
7
8
9


In [31]:
num=10
for i in range(10):
    if i<num:
        print(i)
    if i*2==num:
        break

0
1
2
3
4
5


In [33]:

num=10
for i in range(10):
    if i==5 :
        continue
    if i<num:
        print(i)

0
1
2
3
4
6
7
8
9


In [35]:
num=10
for i in range(10):
    if i==5 :
        pass#不执行任何处理操作
    if i<num:
        print(i)

0
1
2
3
4
5
6
7
8
9


函数

In [36]:
def func():
    print("HELLO WORLD")
    return 
a=func()
print(a)

HELLO WORLD
None


In [38]:
def func(string ="panda"):
    print("What you say is:",string )
    return 
func()
func(string="bumu")
func("bumu")

What you say is: panda
What you say is: bumu
What you say is: bumu


函数的参数 必备参数 关键字参数 默认参数 不定长参数

In [39]:
def func1(string):
    print("what  you want is:",string )
    return 
def func2(string="panda"):
    print("what you want is:",string )
    return 
def func3(string2="world",string1="hello"):
    print("just print",string1,string2)
    return 
def func4(arg1,*arg2):
    print(arg1)
    for i in arg2:
        print(i)
    return 
func1("??")
func2()
func3()
func4(1,23,12,31)



what  you want is: ??
what you want is: panda
just print hello world
1
23
12
31


python中的类 创建


- 类变量
-  _init_()
-  self 类实例


In [41]:
class stu:
    stu_num=0
    def __init__(self,name,age):
        self.name=name
        self.age=age
        stu.stu_num+=1
    
    def dis_stu(self):
        print(self.name,self.age)
    
    stu1=stu("libai","10")
    stu2=stu("wulei","3")
    stu1.dis_stu()
    stu2.dis_stu()
    print(stu.stu_num)

libai 10
wulei 3
2


类的继承

In [44]:
class peo:
    def __init__(self,name,age):
        self.name=name
        self.age=age
    def dis_name(self):
        print("name is",self.name)
    def dis_age(self):
        print("age:",self.age)
    def dis(self):
        print("age name",self.age,self.name)
    def set_age(self,age):
        self.age=age
class stu(peo):
    def __init__(self,name,age,school):
        self.name=name
        self.age=age
        self.school=school
    def dis_school(self):
        print("school",self.school)

stu=stu("WU","3","HD")
stu.dis_school()#调用子类
stu.dis_name()#调用父类
stu.dis_age()
stu.set_age(22)
stu.dis_age()

school HD
name is WU
age: 3
age: 22


类重写

In [48]:
class  par:#定义父类
    def __init__(self):
        pass
    def print_info(self):
        print("This is parent")
class child (par):#定义子类
    def __init__(self):
        pass
    def print_info(self):#重写
        print("kid!!")
c1=child()
c1.print_info()

kid!!


Numpy 科学计算和数据分析基础包

创建多维数组

In [6]:
import numpy as np
np.array([1,2,23,3])


array([ 1,  2, 23,  3])

In [7]:
np.array([[1,2,2],[2,3,4]])

array([[1, 2, 2],
       [2, 3, 4]])

In [8]:
np.ones([2,3])#创建全1数组

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
a=np.ones([2,3])
a[1,2]=2 #注意下标是从0开始的
print(a)

[[1. 1. 1.]
 [1. 1. 2.]]


In [12]:
np.zeros([2,3])#创建全0数组

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.empty([3,3])#创建随机初始化的矩阵

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.18570189e-321],
       [1.78021527e-306, 1.40688321e-311, 0.00000000e+000]])

In [20]:
a=np.ones([2,3])
a.ndim#统计数组的维度的数量

2

In [23]:
a=np.ones([3,2,4])
a.ndim

3

In [24]:
a=np.ones([2,3])
print(a)
print(a.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [25]:
a=np.matrix([[2,3],[32,33]])
print(a)
print(a.shape)

[[ 2  3]
 [32 33]]
(2, 2)


In [26]:
a=np.ones([2,3])
print(a.size)

6


In [30]:
a=np.ones([2,32])
a.dtype

dtype('float64')

In [32]:
s=np.ones([2,3],dtype=np.int32)#重新改写现有元素的类型 
s.dtype

dtype('int32')

In [33]:
s.itemsize#返回每个元素字节的 大小

4

In [35]:
a=np.ones([2,5,3])
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [37]:
a=np.arange(2000)
print(a)

[   0    1    2 ... 1997 1998 1999]


多维数组的基本操作（算数运算，索引，切片，迭代

In [38]:
a=np.array([1,2,3])
b=np.array([2,3,55])
print(a-b)
print(a+b)
print(a*b)#这是数组运算不是矩阵运算 切记 ~~~
print(a/b)

[ -1  -1 -52]
[ 3  5 58]
[  2   6 165]
[0.5        0.66666667 0.05454545]


In [39]:
#那么如何用数组实现矩阵运算
print(a*b)
c=a.dot(b)
print("a*b=",c)
print(np.dot(a,b))

[  2   6 165]
a*b= 173
173


In [40]:
a=np.array([12,3,44])
print(a*2)
print(a/2)
print(a+2)
print(a-2)

[24  6 88]
[ 6.   1.5 22. ]
[14  5 46]
[10  1 42]


数组自身的运算

In [41]:
#min max sum 
print(a.min())
print(a.max())
print(a.sum())

3
44
59


In [43]:
a=np.array([[1,2,3],[3,2,1]])
print(a.min())
print(a.min(axis=0))#对应三列
print(a.min(axis=1))#对应2行
print(a.max())
print(a.max(axis=0))
print(a.max(axis=1))
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

1
[1 2 1]
[1 1]
3
[3 2 3]
[3 3]
12
[4 4 4]
[6 6]


In [44]:
a=np.array([[1,2,3]])
print(np.exp(a))#指数
print(np.sqrt(a))#平方根
print(np.square(a))#平方运算

[[ 2.71828183  7.3890561  20.08553692]]
[[1.         1.41421356 1.73205081]]
[[1 4 9]]


随机数组
- 随机因子确定后，无论我们运行多少次随机程序，最后生成的数字都一样，相当于把随机过程变成一个伪随机的机制
- rand [0,1)
- randn平均值为0 方差为1的正太分布随机样本
- randint 类型为整数的随机样本数
- binomial 生成维度指定且二项分布的随机样本数
- beta 维度指定且符合bata分布的随机样本
-normal 维度指定且符合高斯正太分布的随机样本

In [46]:
a=np.arange(10)
print(a)
print(a[:5])
for i in a:
    print(i)#迭代

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
0
1
2
3
4
5
6
7
8
9


In [48]:
#索引切片
a=np.array([[1,2,3],[4,5,6],[7,8,9]])#qwq每次array的数组都忘记加上一个大括号 
print(a)
print("-"*10)
print(a[1])#输出指定维度的数据
print("-"*10)
print(a[0:2,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[4 5 6]
----------
[[2 3]
 [5 6]]


In [49]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in a:
    print(i)
    
print("-"*10)
for i in a:
    for j  in i:
        print(j)

[1 2 3]
[4 5 6]
[7 8 9]
----------
1
2
3
4
5
6
7
8
9


In [51]:
#也可以选择扁平化处理
for i in a.flat:
    print(i)

1
2
3
4
5
6
7
8
9
