In [2]:
import torch 
a=torch.FloatTensor(2,3)
b=torch.FloatTensor([2,3,4,5])
print(a)
print(b)

tensor([[2.6728e+23, 8.5491e+20, 2.1414e+23],
        [1.6800e-07, 1.0387e+21, 2.6193e+20]])
tensor([2., 3., 4., 5.])


In [3]:
a=torch.IntTensor(2,3)
b=torch.IntTensor([2,3,4,5])
print(a)
print(b)

tensor([[1413494016,        494, 1394417816],
        [       494,          0,          0]], dtype=torch.int32)
tensor([2, 3, 4, 5], dtype=torch.int32)


In [4]:
a=torch.rand(2,3)#01之间
print(a)

tensor([[0.2078, 0.7800, 0.8844],
        [0.9591, 0.2227, 0.8226]])


In [5]:
a=torch.randn(2,3)
print(a)

tensor([[ 0.3736, -0.0142, -1.2559],
        [-0.5375, -0.5747, -0.8247]])


In [7]:
a=torch.arange(1,20,1)
print(a)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])


In [8]:
a=torch.zeros(2,3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
a=torch.randn(2,3)
print(a)
b=torch.abs(a)
print(b)

tensor([[-0.3563, -0.5440, -0.4415],
        [-1.5780, -0.8036,  0.3688]])
tensor([[0.3563, 0.5440, 0.4415],
        [1.5780, 0.8036, 0.3688]])


In [11]:
a=torch.randn(2,3)
b=torch.randn(2,3)
print(a)
print(b)
c=torch.add(a,b)
print(c)
d=torch.randn(2,3)
print(d)
e=torch.add(d,10)
print(e)

tensor([[-1.7642,  1.7510,  0.0584],
        [ 0.1990, -0.4555,  0.7671]])
tensor([[-1.4578, -0.2923,  1.4052],
        [-0.2957,  0.1927, -0.8370]])
tensor([[-3.2220,  1.4586,  1.4636],
        [-0.0967, -0.2628, -0.0699]])
tensor([[ 0.5175, -0.5988,  1.1828],
        [ 1.8924, -0.3877,  1.5579]])
tensor([[10.5175,  9.4012, 11.1828],
        [11.8924,  9.6123, 11.5579]])


In [12]:
#torch.clamp实现剪裁
#对应三个参数 变量 裁剪的上边界 裁剪的下边界
print(a)
b=torch.clamp(a,-0.1,0.1)
print(b)

tensor([[-1.7642,  1.7510,  0.0584],
        [ 0.1990, -0.4555,  0.7671]])
tensor([[-0.1000,  0.1000,  0.0584],
        [ 0.1000, -0.1000,  0.1000]])


In [16]:
#torch.div 
a=torch.randn(2,3)
print(a)
b=torch.randn(2,3)
print(b)
c=torch.div(a,b)
d=torch.div(a,10)
print(c)
print(d)

tensor([[-0.4351, -0.2045, -0.4725],
        [ 0.3752,  0.6113, -1.1406]])
tensor([[-0.4886,  1.3802, -1.3198],
        [-0.5407, -0.3759,  0.6099]])
tensor([[ 0.8905, -0.1481,  0.3580],
        [-0.6938, -1.6263, -1.8702]])
tensor([[-0.0435, -0.0204, -0.0473],
        [ 0.0375,  0.0611, -0.1141]])


In [17]:
a=torch.randn(2,3)
b=torch.randn(2,3)
c=torch.mul(a,b)
d=torch.randn(2,3)
e=torch.mul(d,10)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[-0.5555,  0.3055, -0.2937],
        [ 0.3728,  0.3885, -1.1094]])
tensor([[-1.4202,  0.5078, -0.8459],
        [ 1.2372, -0.1607, -0.8424]])
tensor([[ 0.7890,  0.1551,  0.2484],
        [ 0.4613, -0.0624,  0.9346]])
tensor([[-0.9341,  1.5351,  1.0407],
        [-0.5631,  1.5236, -0.2063]])
tensor([[-9.3407, 15.3514, 10.4074],
        [-5.6309, 15.2365, -2.0627]])


In [19]:
c=torch.mul(a,b)
d=torch.mul(a,10)
print(c)
print(d)

tensor([[ 0.7890,  0.1551,  0.2484],
        [ 0.4613, -0.0624,  0.9346]])
tensor([[ -5.5553,   3.0551,  -2.9372],
        [  3.7284,   3.8853, -11.0945]])


In [20]:
b=torch.pow(a,2)
d=torch.pow(a,3)
print(b)
print(d)

tensor([[0.3086, 0.0933, 0.0863],
        [0.1390, 0.1510, 1.2309]])
tensor([[-0.1714,  0.0285, -0.0253],
        [ 0.0518,  0.0587, -1.3656]])


In [21]:
#这次是矩阵乘法上次是直接乘
a=torch.randn(2,3)
b=torch.randn(3,2)
c=torch.mm(a,b)
print(a)
print(b)
print(c)

tensor([[ 0.3433,  0.0637, -0.7685],
        [ 0.2135,  0.0627,  1.6115]])
tensor([[-0.5995,  0.0461],
        [ 1.1289,  0.0201],
        [-0.6063,  0.0703]])
tensor([[ 0.3321, -0.0369],
        [-1.0344,  0.1243]])


In [22]:
#torch.mv 矩阵乘向量
a=torch.randn(2,3)
b=torch.randn(3)
print(a)
print(b)
c=torch.mv(a,b)
print(c)

tensor([[ 1.1373, -0.1533, -0.8565],
        [ 0.9704,  0.1244,  0.7444]])
tensor([1.0042, 0.4753, 1.7861])
tensor([-0.4607,  2.3632])
